theme: jekyll-theme-cayman

# Dice a GitHub di applicare il tema a TUTTI i file .md, non solo alla index
plugins:
  - jekyll-optional-front-matter

# Impedisce a GitHub di nascondere i file che iniziano con l'underscore
exclude: []
